### PR TITLE
Add `JsonField` plugin

### PR DESCRIPTION
**Pull request by jcredding**
This adds a `JsonField` plugin for handling json columns. This
handles reading json encoded strings to and from the db and
decoding them. It also encodes new values into json encoded strings
when writing fields. This also includes plugins for records and
fake records which ensure json columns are synced before a record
is saved.

The `JsonField` is a mixin that can be used on models and read
models. It provides a DSL for defining json field accessors,
readers and writers. A json field reader adds a reader method that
reads from a source attribute (expecting a json encoded string) and
returns the decoded value. The json field writer adds a writer
method that takes a value and encodes it, writing it to its source
attribute. The `JsonField` also tracks its json field names and
json source field names which allows inspecting what has been
configured and also is needed for the record/fake record mixin.

The `JsonField` comes with a default json encoder and decoder that
it uses for encoding and decoding json values in json field
readers and writers. The default encoder and decoder use the `JSON`
gem/module but this can be overwritten using the writers on the
`JsonFIeld` module. The `JSON` gem is not required by default and
must be brought in for the defaults to work. This is for ruby 1.8.7
compatibility. For ruby 1.9 and later the `JSON` module just needs
to be required from the standard library.

The `Record` and `FakeRecord` mixins handle syncing up json fields
with their source attributes. This is needed because json fields
can be modified without using the json field writer. For example,
hashes and arrays can be modified by adding new items or
key-values. Since the writer isn't used these changes won't be
persisted to the source attribute. The record adds a before save
callback that uses the configured json field accessors from its
model, reads their current values and writes them using their
writer. This makes them update their source attributes as expected.
The fake record does the same logic only it overwrites the `save!`
method, syncs the json fields and then supers.

Finally, this includes test helpers which make it easy to test that
a class has json fields configured. This avoids having to know
internals to how json field works.

@kellyredding - Ready for review.

### CODE REVIEW

**Comment by kellyredding** [comment]
@jcredding "... handles reading json encoded strings *to* and from the db and..."

**Comment by kellyredding** [comment]
@jcredding could you maybe discuss the encoder/decoder API, its purpose, and how it uses JSON by default in the commit msg?

**Comment by kellyredding** [comment]
@jcredding I'm assuming this is close to what it is extracted from, implementation-wise?  Any major departures (besides configuring the encoder/decoder)?  I noticed some differences in the main implementation (haven't scoured the tests yet), but everything seems like changes to be more thorough or straight-forward).

**Comment by kellyredding** [comment]
@jcredding how did we get away with not having a fake record mixin in the thing we extracted this from?

**Comment by kellyredding** [comment]
@jcredding a couple of questions - otherwise 👎

**Comment by jcredding** [comment]
@kellyredding - Yeah, the big differences between this and what it was extracted from are that it has a configurable encoder/decoder and I added the `FakeRecord` mixin. There were a few other smaller changes:
* The reader and writer rescue standard errors that come from encoding/decoding and raise an invalid json error. This was copied for the reader but I added it for the writer. This should help with debugging
which field is being written to with invalid json and where its happening.
* I added methods for the `json_field_readers` and `json_field_writers` and used them when adding field names to their collections. These were just ivars in what I extracted the json logic from but having the methods allowed removing code that optionally set the ivars to an array everytime a DSL method was called.
* I reworked the tests to provide more coverage and break them into smaller chunks. Specifically, I broke up testing the individual DSL methods into different tests and added tests for fields with a custom source. I also split testing the DSL methods from testing the instance methods that are defined by calling the DSL method into different contexts. I felt this provided better organization.

As far as the `FakeRecord` mixin goes, I'm mostly providing it for completeness. In our usage of JSON fields it doesn't provide much for us because we never check the source in our tests. This is mostly due to the JSON string being hard to compare values against because it may reorder hash keys. So for us, it hasn't mattered that the source field may not match the json field. So, while this doesn't fix an issue or fill a current need for us, I felt it was more complete. There are probably edge cases where having this would be needed that we just haven't run into. One thing I like that it does is if we modify a json field not using the writer, like adding a new key-value to a hash and that somehow creates invalid json, this will error now where it previously wouldn't.

**Comment by kellyredding** [comment]
@jcredding that all makes sense and was helpful to know - thanks man.  Update the commit msg and I'm good here 👎

**Pull request merged**
